/*
ai-proto

ai proto for coder

API version: 0.0.1
Contact: panleiming@linksaas.pro
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the ApiCodingExplainLangPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiCodingExplainLangPostRequest{}

// ApiCodingExplainLangPostRequest struct for ApiCodingExplainLangPostRequest
type ApiCodingExplainLangPostRequest struct {
	// 代码内容
	Content string `json:"content"`
}

// NewApiCodingExplainLangPostRequest instantiates a new ApiCodingExplainLangPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiCodingExplainLangPostRequest(content string) *ApiCodingExplainLangPostRequest {
	this := ApiCodingExplainLangPostRequest{}
	this.Content = content
	return &this
}

// NewApiCodingExplainLangPostRequestWithDefaults instantiates a new ApiCodingExplainLangPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiCodingExplainLangPostRequestWithDefaults() *ApiCodingExplainLangPostRequest {
	this := ApiCodingExplainLangPostRequest{}
	return &this
}

// GetContent returns the Content field value
func (o *ApiCodingExplainLangPostRequest) GetContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *ApiCodingExplainLangPostRequest) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *ApiCodingExplainLangPostRequest) SetContent(v string) {
	o.Content = v
}

func (o ApiCodingExplainLangPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiCodingExplainLangPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["content"] = o.Content
	return toSerialize, nil
}

type NullableApiCodingExplainLangPostRequest struct {
	value *ApiCodingExplainLangPostRequest
	isSet bool
}

func (v NullableApiCodingExplainLangPostRequest) Get() *ApiCodingExplainLangPostRequest {
	return v.value
}

func (v *NullableApiCodingExplainLangPostRequest) Set(val *ApiCodingExplainLangPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiCodingExplainLangPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiCodingExplainLangPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiCodingExplainLangPostRequest(val *ApiCodingExplainLangPostRequest) *NullableApiCodingExplainLangPostRequest {
	return &NullableApiCodingExplainLangPostRequest{value: val, isSet: true}
}

func (v NullableApiCodingExplainLangPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiCodingExplainLangPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


