/*
ai-proto

ai proto for coder

API version: 0.0.2
Contact: panleiming@linksaas.pro
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the ApiCodingFixErrorLangPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiCodingFixErrorLangPostRequest{}

// ApiCodingFixErrorLangPostRequest struct for ApiCodingFixErrorLangPostRequest
type ApiCodingFixErrorLangPostRequest struct {
	// 报错内容
	Content string `json:"content"`
}

// NewApiCodingFixErrorLangPostRequest instantiates a new ApiCodingFixErrorLangPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiCodingFixErrorLangPostRequest(content string) *ApiCodingFixErrorLangPostRequest {
	this := ApiCodingFixErrorLangPostRequest{}
	this.Content = content
	return &this
}

// NewApiCodingFixErrorLangPostRequestWithDefaults instantiates a new ApiCodingFixErrorLangPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiCodingFixErrorLangPostRequestWithDefaults() *ApiCodingFixErrorLangPostRequest {
	this := ApiCodingFixErrorLangPostRequest{}
	return &this
}

// GetContent returns the Content field value
func (o *ApiCodingFixErrorLangPostRequest) GetContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *ApiCodingFixErrorLangPostRequest) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *ApiCodingFixErrorLangPostRequest) SetContent(v string) {
	o.Content = v
}

func (o ApiCodingFixErrorLangPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiCodingFixErrorLangPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["content"] = o.Content
	return toSerialize, nil
}

type NullableApiCodingFixErrorLangPostRequest struct {
	value *ApiCodingFixErrorLangPostRequest
	isSet bool
}

func (v NullableApiCodingFixErrorLangPostRequest) Get() *ApiCodingFixErrorLangPostRequest {
	return v.value
}

func (v *NullableApiCodingFixErrorLangPostRequest) Set(val *ApiCodingFixErrorLangPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiCodingFixErrorLangPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiCodingFixErrorLangPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiCodingFixErrorLangPostRequest(val *ApiCodingFixErrorLangPostRequest) *NullableApiCodingFixErrorLangPostRequest {
	return &NullableApiCodingFixErrorLangPostRequest{value: val, isSet: true}
}

func (v NullableApiCodingFixErrorLangPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiCodingFixErrorLangPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


