/*
ai-proto

ai proto for coder

API version: 0.0.2
Contact: panleiming@linksaas.pro
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the ApiDevCapPost200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiDevCapPost200Response{}

// ApiDevCapPost200Response struct for ApiDevCapPost200Response
type ApiDevCapPost200Response struct {
	// 代码补全支持的编程语言列表
	CompleteLangList []Lang `json:"completeLangList"`
	// 生成测试代码支持的编程语言列表
	GenTestLangList []Lang `json:"genTestLangList"`
	// 转换编程语言的支持列表
	ConvertLangList []Lang `json:"convertLangList"`
	// 代码解释支持的编程语言列表
	ExplainLangList []Lang `json:"explainLangList"`
	// 根据错误提示给出修复方案支持的编程语言列表
	FixErrorLangList []Lang `json:"fixErrorLangList"`
}

// NewApiDevCapPost200Response instantiates a new ApiDevCapPost200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiDevCapPost200Response(completeLangList []Lang, genTestLangList []Lang, convertLangList []Lang, explainLangList []Lang, fixErrorLangList []Lang) *ApiDevCapPost200Response {
	this := ApiDevCapPost200Response{}
	this.CompleteLangList = completeLangList
	this.GenTestLangList = genTestLangList
	this.ConvertLangList = convertLangList
	this.ExplainLangList = explainLangList
	this.FixErrorLangList = fixErrorLangList
	return &this
}

// NewApiDevCapPost200ResponseWithDefaults instantiates a new ApiDevCapPost200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiDevCapPost200ResponseWithDefaults() *ApiDevCapPost200Response {
	this := ApiDevCapPost200Response{}
	return &this
}

// GetCompleteLangList returns the CompleteLangList field value
func (o *ApiDevCapPost200Response) GetCompleteLangList() []Lang {
	if o == nil {
		var ret []Lang
		return ret
	}

	return o.CompleteLangList
}

// GetCompleteLangListOk returns a tuple with the CompleteLangList field value
// and a boolean to check if the value has been set.
func (o *ApiDevCapPost200Response) GetCompleteLangListOk() ([]Lang, bool) {
	if o == nil {
		return nil, false
	}
	return o.CompleteLangList, true
}

// SetCompleteLangList sets field value
func (o *ApiDevCapPost200Response) SetCompleteLangList(v []Lang) {
	o.CompleteLangList = v
}

// GetGenTestLangList returns the GenTestLangList field value
func (o *ApiDevCapPost200Response) GetGenTestLangList() []Lang {
	if o == nil {
		var ret []Lang
		return ret
	}

	return o.GenTestLangList
}

// GetGenTestLangListOk returns a tuple with the GenTestLangList field value
// and a boolean to check if the value has been set.
func (o *ApiDevCapPost200Response) GetGenTestLangListOk() ([]Lang, bool) {
	if o == nil {
		return nil, false
	}
	return o.GenTestLangList, true
}

// SetGenTestLangList sets field value
func (o *ApiDevCapPost200Response) SetGenTestLangList(v []Lang) {
	o.GenTestLangList = v
}

// GetConvertLangList returns the ConvertLangList field value
func (o *ApiDevCapPost200Response) GetConvertLangList() []Lang {
	if o == nil {
		var ret []Lang
		return ret
	}

	return o.ConvertLangList
}

// GetConvertLangListOk returns a tuple with the ConvertLangList field value
// and a boolean to check if the value has been set.
func (o *ApiDevCapPost200Response) GetConvertLangListOk() ([]Lang, bool) {
	if o == nil {
		return nil, false
	}
	return o.ConvertLangList, true
}

// SetConvertLangList sets field value
func (o *ApiDevCapPost200Response) SetConvertLangList(v []Lang) {
	o.ConvertLangList = v
}

// GetExplainLangList returns the ExplainLangList field value
func (o *ApiDevCapPost200Response) GetExplainLangList() []Lang {
	if o == nil {
		var ret []Lang
		return ret
	}

	return o.ExplainLangList
}

// GetExplainLangListOk returns a tuple with the ExplainLangList field value
// and a boolean to check if the value has been set.
func (o *ApiDevCapPost200Response) GetExplainLangListOk() ([]Lang, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExplainLangList, true
}

// SetExplainLangList sets field value
func (o *ApiDevCapPost200Response) SetExplainLangList(v []Lang) {
	o.ExplainLangList = v
}

// GetFixErrorLangList returns the FixErrorLangList field value
func (o *ApiDevCapPost200Response) GetFixErrorLangList() []Lang {
	if o == nil {
		var ret []Lang
		return ret
	}

	return o.FixErrorLangList
}

// GetFixErrorLangListOk returns a tuple with the FixErrorLangList field value
// and a boolean to check if the value has been set.
func (o *ApiDevCapPost200Response) GetFixErrorLangListOk() ([]Lang, bool) {
	if o == nil {
		return nil, false
	}
	return o.FixErrorLangList, true
}

// SetFixErrorLangList sets field value
func (o *ApiDevCapPost200Response) SetFixErrorLangList(v []Lang) {
	o.FixErrorLangList = v
}

func (o ApiDevCapPost200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiDevCapPost200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["completeLangList"] = o.CompleteLangList
	toSerialize["genTestLangList"] = o.GenTestLangList
	toSerialize["convertLangList"] = o.ConvertLangList
	toSerialize["explainLangList"] = o.ExplainLangList
	toSerialize["fixErrorLangList"] = o.FixErrorLangList
	return toSerialize, nil
}

type NullableApiDevCapPost200Response struct {
	value *ApiDevCapPost200Response
	isSet bool
}

func (v NullableApiDevCapPost200Response) Get() *ApiDevCapPost200Response {
	return v.value
}

func (v *NullableApiDevCapPost200Response) Set(val *ApiDevCapPost200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiDevCapPost200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiDevCapPost200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiDevCapPost200Response(val *ApiDevCapPost200Response) *NullableApiDevCapPost200Response {
	return &NullableApiDevCapPost200Response{value: val, isSet: true}
}

func (v NullableApiDevCapPost200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiDevCapPost200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


