/*
ai-proto

ai proto for coder

API version: 0.0.3
Contact: panleiming@linksaas.pro
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the ApiDevGenTokenPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiDevGenTokenPostRequest{}

// ApiDevGenTokenPostRequest struct for ApiDevGenTokenPostRequest
type ApiDevGenTokenPostRequest struct {
	// 上下文信息
	ContextValue string `json:"contextValue" xml:"contextValue"`
	// 随机字符串，加密因子。需要32位长度以上
	RandomStr string `json:"randomStr" xml:"randomStr"`
}

// NewApiDevGenTokenPostRequest instantiates a new ApiDevGenTokenPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiDevGenTokenPostRequest(contextValue string, randomStr string) *ApiDevGenTokenPostRequest {
	this := ApiDevGenTokenPostRequest{}
	this.ContextValue = contextValue
	this.RandomStr = randomStr
	return &this
}

// NewApiDevGenTokenPostRequestWithDefaults instantiates a new ApiDevGenTokenPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiDevGenTokenPostRequestWithDefaults() *ApiDevGenTokenPostRequest {
	this := ApiDevGenTokenPostRequest{}
	return &this
}

// GetContextValue returns the ContextValue field value
func (o *ApiDevGenTokenPostRequest) GetContextValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContextValue
}

// GetContextValueOk returns a tuple with the ContextValue field value
// and a boolean to check if the value has been set.
func (o *ApiDevGenTokenPostRequest) GetContextValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContextValue, true
}

// SetContextValue sets field value
func (o *ApiDevGenTokenPostRequest) SetContextValue(v string) {
	o.ContextValue = v
}

// GetRandomStr returns the RandomStr field value
func (o *ApiDevGenTokenPostRequest) GetRandomStr() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RandomStr
}

// GetRandomStrOk returns a tuple with the RandomStr field value
// and a boolean to check if the value has been set.
func (o *ApiDevGenTokenPostRequest) GetRandomStrOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RandomStr, true
}

// SetRandomStr sets field value
func (o *ApiDevGenTokenPostRequest) SetRandomStr(v string) {
	o.RandomStr = v
}

func (o ApiDevGenTokenPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiDevGenTokenPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["contextValue"] = o.ContextValue
	toSerialize["randomStr"] = o.RandomStr
	return toSerialize, nil
}

type NullableApiDevGenTokenPostRequest struct {
	value *ApiDevGenTokenPostRequest
	isSet bool
}

func (v NullableApiDevGenTokenPostRequest) Get() *ApiDevGenTokenPostRequest {
	return v.value
}

func (v *NullableApiDevGenTokenPostRequest) Set(val *ApiDevGenTokenPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiDevGenTokenPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiDevGenTokenPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiDevGenTokenPostRequest(val *ApiDevGenTokenPostRequest) *NullableApiDevGenTokenPostRequest {
	return &NullableApiDevGenTokenPostRequest{value: val, isSet: true}
}

func (v NullableApiDevGenTokenPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiDevGenTokenPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


