/*
ai-proto

ai proto for coder

API version: 0.0.3
Contact: panleiming@linksaas.pro
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the ApiCodingFixErrorLangPost200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiCodingFixErrorLangPost200Response{}

// ApiCodingFixErrorLangPost200Response struct for ApiCodingFixErrorLangPost200Response
type ApiCodingFixErrorLangPost200Response struct {
	// 修复方案候选列表
	Data []string `json:"data" xml:"data"`
}

// NewApiCodingFixErrorLangPost200Response instantiates a new ApiCodingFixErrorLangPost200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiCodingFixErrorLangPost200Response(data []string) *ApiCodingFixErrorLangPost200Response {
	this := ApiCodingFixErrorLangPost200Response{}
	this.Data = data
	return &this
}

// NewApiCodingFixErrorLangPost200ResponseWithDefaults instantiates a new ApiCodingFixErrorLangPost200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiCodingFixErrorLangPost200ResponseWithDefaults() *ApiCodingFixErrorLangPost200Response {
	this := ApiCodingFixErrorLangPost200Response{}
	return &this
}

// GetData returns the Data field value
func (o *ApiCodingFixErrorLangPost200Response) GetData() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ApiCodingFixErrorLangPost200Response) GetDataOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ApiCodingFixErrorLangPost200Response) SetData(v []string) {
	o.Data = v
}

func (o ApiCodingFixErrorLangPost200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiCodingFixErrorLangPost200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

type NullableApiCodingFixErrorLangPost200Response struct {
	value *ApiCodingFixErrorLangPost200Response
	isSet bool
}

func (v NullableApiCodingFixErrorLangPost200Response) Get() *ApiCodingFixErrorLangPost200Response {
	return v.value
}

func (v *NullableApiCodingFixErrorLangPost200Response) Set(val *ApiCodingFixErrorLangPost200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiCodingFixErrorLangPost200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiCodingFixErrorLangPost200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiCodingFixErrorLangPost200Response(val *ApiCodingFixErrorLangPost200Response) *NullableApiCodingFixErrorLangPost200Response {
	return &NullableApiCodingFixErrorLangPost200Response{value: val, isSet: true}
}

func (v NullableApiCodingFixErrorLangPost200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiCodingFixErrorLangPost200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


