/*
ai-proto

ai proto for coder

API version: 0.0.3
Contact: panleiming@linksaas.pro
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the ApiCodingCompleteLangPost200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiCodingCompleteLangPost200Response{}

// ApiCodingCompleteLangPost200Response struct for ApiCodingCompleteLangPost200Response
type ApiCodingCompleteLangPost200Response struct {
	// 生成代码候选列表
	Data []string `json:"data" xml:"data"`
}

// NewApiCodingCompleteLangPost200Response instantiates a new ApiCodingCompleteLangPost200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiCodingCompleteLangPost200Response(data []string) *ApiCodingCompleteLangPost200Response {
	this := ApiCodingCompleteLangPost200Response{}
	this.Data = data
	return &this
}

// NewApiCodingCompleteLangPost200ResponseWithDefaults instantiates a new ApiCodingCompleteLangPost200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiCodingCompleteLangPost200ResponseWithDefaults() *ApiCodingCompleteLangPost200Response {
	this := ApiCodingCompleteLangPost200Response{}
	return &this
}

// GetData returns the Data field value
func (o *ApiCodingCompleteLangPost200Response) GetData() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ApiCodingCompleteLangPost200Response) GetDataOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ApiCodingCompleteLangPost200Response) SetData(v []string) {
	o.Data = v
}

func (o ApiCodingCompleteLangPost200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiCodingCompleteLangPost200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

type NullableApiCodingCompleteLangPost200Response struct {
	value *ApiCodingCompleteLangPost200Response
	isSet bool
}

func (v NullableApiCodingCompleteLangPost200Response) Get() *ApiCodingCompleteLangPost200Response {
	return v.value
}

func (v *NullableApiCodingCompleteLangPost200Response) Set(val *ApiCodingCompleteLangPost200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiCodingCompleteLangPost200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiCodingCompleteLangPost200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiCodingCompleteLangPost200Response(val *ApiCodingCompleteLangPost200Response) *NullableApiCodingCompleteLangPost200Response {
	return &NullableApiCodingCompleteLangPost200Response{value: val, isSet: true}
}

func (v NullableApiCodingCompleteLangPost200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiCodingCompleteLangPost200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


