/*
ai-proto

ai proto for coder

API version: 0.0.3
Contact: panleiming@linksaas.pro
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the ApiCodingExplainLangPost200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiCodingExplainLangPost200Response{}

// ApiCodingExplainLangPost200Response struct for ApiCodingExplainLangPost200Response
type ApiCodingExplainLangPost200Response struct {
	// 生成解释结果候选列表
	Data []string `json:"data" xml:"data"`
}

// NewApiCodingExplainLangPost200Response instantiates a new ApiCodingExplainLangPost200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiCodingExplainLangPost200Response(data []string) *ApiCodingExplainLangPost200Response {
	this := ApiCodingExplainLangPost200Response{}
	this.Data = data
	return &this
}

// NewApiCodingExplainLangPost200ResponseWithDefaults instantiates a new ApiCodingExplainLangPost200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiCodingExplainLangPost200ResponseWithDefaults() *ApiCodingExplainLangPost200Response {
	this := ApiCodingExplainLangPost200Response{}
	return &this
}

// GetData returns the Data field value
func (o *ApiCodingExplainLangPost200Response) GetData() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ApiCodingExplainLangPost200Response) GetDataOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ApiCodingExplainLangPost200Response) SetData(v []string) {
	o.Data = v
}

func (o ApiCodingExplainLangPost200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiCodingExplainLangPost200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

type NullableApiCodingExplainLangPost200Response struct {
	value *ApiCodingExplainLangPost200Response
	isSet bool
}

func (v NullableApiCodingExplainLangPost200Response) Get() *ApiCodingExplainLangPost200Response {
	return v.value
}

func (v *NullableApiCodingExplainLangPost200Response) Set(val *ApiCodingExplainLangPost200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiCodingExplainLangPost200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiCodingExplainLangPost200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiCodingExplainLangPost200Response(val *ApiCodingExplainLangPost200Response) *NullableApiCodingExplainLangPost200Response {
	return &NullableApiCodingExplainLangPost200Response{value: val, isSet: true}
}

func (v NullableApiCodingExplainLangPost200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiCodingExplainLangPost200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


