/*
ai-proto

ai proto for coder

API version: 0.0.3
Contact: panleiming@linksaas.pro
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the ApiDevCapPost200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiDevCapPost200Response{}

// ApiDevCapPost200Response struct for ApiDevCapPost200Response
type ApiDevCapPost200Response struct {
	Coding ApiDevCapPost200ResponseCoding `json:"coding" xml:"coding"`
}

// NewApiDevCapPost200Response instantiates a new ApiDevCapPost200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiDevCapPost200Response(coding ApiDevCapPost200ResponseCoding) *ApiDevCapPost200Response {
	this := ApiDevCapPost200Response{}
	this.Coding = coding
	return &this
}

// NewApiDevCapPost200ResponseWithDefaults instantiates a new ApiDevCapPost200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiDevCapPost200ResponseWithDefaults() *ApiDevCapPost200Response {
	this := ApiDevCapPost200Response{}
	return &this
}

// GetCoding returns the Coding field value
func (o *ApiDevCapPost200Response) GetCoding() ApiDevCapPost200ResponseCoding {
	if o == nil {
		var ret ApiDevCapPost200ResponseCoding
		return ret
	}

	return o.Coding
}

// GetCodingOk returns a tuple with the Coding field value
// and a boolean to check if the value has been set.
func (o *ApiDevCapPost200Response) GetCodingOk() (*ApiDevCapPost200ResponseCoding, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Coding, true
}

// SetCoding sets field value
func (o *ApiDevCapPost200Response) SetCoding(v ApiDevCapPost200ResponseCoding) {
	o.Coding = v
}

func (o ApiDevCapPost200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiDevCapPost200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["coding"] = o.Coding
	return toSerialize, nil
}

type NullableApiDevCapPost200Response struct {
	value *ApiDevCapPost200Response
	isSet bool
}

func (v NullableApiDevCapPost200Response) Get() *ApiDevCapPost200Response {
	return v.value
}

func (v *NullableApiDevCapPost200Response) Set(val *ApiDevCapPost200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiDevCapPost200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiDevCapPost200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiDevCapPost200Response(val *ApiDevCapPost200Response) *NullableApiDevCapPost200Response {
	return &NullableApiDevCapPost200Response{value: val, isSet: true}
}

func (v NullableApiDevCapPost200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiDevCapPost200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


