/*
ai-proto

ai proto for coder

API version: 0.0.3
Contact: panleiming@linksaas.pro
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the ApiCodingConvertLangPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiCodingConvertLangPostRequest{}

// ApiCodingConvertLangPostRequest struct for ApiCodingConvertLangPostRequest
type ApiCodingConvertLangPostRequest struct {
	// 代码内容
	Content string `json:"content" xml:"content"`
	DestLang Lang `json:"destLang" xml:"destLang"`
}

// NewApiCodingConvertLangPostRequest instantiates a new ApiCodingConvertLangPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiCodingConvertLangPostRequest(content string, destLang Lang) *ApiCodingConvertLangPostRequest {
	this := ApiCodingConvertLangPostRequest{}
	this.Content = content
	this.DestLang = destLang
	return &this
}

// NewApiCodingConvertLangPostRequestWithDefaults instantiates a new ApiCodingConvertLangPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiCodingConvertLangPostRequestWithDefaults() *ApiCodingConvertLangPostRequest {
	this := ApiCodingConvertLangPostRequest{}
	return &this
}

// GetContent returns the Content field value
func (o *ApiCodingConvertLangPostRequest) GetContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *ApiCodingConvertLangPostRequest) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *ApiCodingConvertLangPostRequest) SetContent(v string) {
	o.Content = v
}

// GetDestLang returns the DestLang field value
func (o *ApiCodingConvertLangPostRequest) GetDestLang() Lang {
	if o == nil {
		var ret Lang
		return ret
	}

	return o.DestLang
}

// GetDestLangOk returns a tuple with the DestLang field value
// and a boolean to check if the value has been set.
func (o *ApiCodingConvertLangPostRequest) GetDestLangOk() (*Lang, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DestLang, true
}

// SetDestLang sets field value
func (o *ApiCodingConvertLangPostRequest) SetDestLang(v Lang) {
	o.DestLang = v
}

func (o ApiCodingConvertLangPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiCodingConvertLangPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["content"] = o.Content
	toSerialize["destLang"] = o.DestLang
	return toSerialize, nil
}

type NullableApiCodingConvertLangPostRequest struct {
	value *ApiCodingConvertLangPostRequest
	isSet bool
}

func (v NullableApiCodingConvertLangPostRequest) Get() *ApiCodingConvertLangPostRequest {
	return v.value
}

func (v *NullableApiCodingConvertLangPostRequest) Set(val *ApiCodingConvertLangPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiCodingConvertLangPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiCodingConvertLangPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiCodingConvertLangPostRequest(val *ApiCodingConvertLangPostRequest) *NullableApiCodingConvertLangPostRequest {
	return &NullableApiCodingConvertLangPostRequest{value: val, isSet: true}
}

func (v NullableApiCodingConvertLangPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiCodingConvertLangPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


