/*
 * ai-proto
 *
 * ai proto for coder
 *
 * API version: 0.0.1
 * Contact: panleiming@linksaas.pro
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// ApiDevGenTokenCapGet - 获取ai能力列表
func ApiDevGenTokenCapGet(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ApiDevGenTokenPost - 生成authToken,只在开发模式下有效
func ApiDevGenTokenPost(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
