/*
 * ai-proto
 *
 * ai proto for coder
 *
 * API version: 0.0.1
 * Contact: panleiming@linksaas.pro
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

type ApiCodingFixErrorLangPostRequest struct {

	// 报错内容
	Content string `json:"content"`
}
