/*
 * ai-proto
 *
 * ai proto for coder
 *
 * API version: 0.0.1
 * Contact: panleiming@linksaas.pro
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

type ApiCodingConvertLangPostRequest struct {

	// 代码内容
	Content string `json:"content"`

	DestLang Lang `json:"destLang"`
}
