/*
 * ai-proto
 *
 * ai proto for coder
 *
 * API version: 0.0.1
 * Contact: panleiming@linksaas.pro
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

type ApiDevGenTokenCapGet200Response struct {

	// 代码补全支持的编程语言列表
	CompleteLangList []Lang `json:"completeLangList"`

	// 生成测试代码支持的编程语言列表
	GenTestLangList []Lang `json:"genTestLangList"`

	// 转换编程语言的支持列表
	ConvertLangList []Lang `json:"convertLangList"`

	// 代码解释支持的编程语言列表
	ExplainLangList []Lang `json:"explainLangList"`

	// 根据错误提示给出修复方案支持的编程语言列表
	FixErrorLangList []Lang `json:"fixErrorLangList"`
}
