/*
 * ai-proto
 *
 * ai proto for coder
 *
 * API version: 0.0.2
 * Contact: panleiming@linksaas.pro
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

type ApiCodingExplainLangPostRequest struct {

	// 代码内容
	Content string `json:"content"`
}
