/*
 * ai-proto
 *
 * ai proto for coder
 *
 * API version: 0.0.2
 * Contact: panleiming@linksaas.pro
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server
// Lang : 编程语言
type Lang string

// List of Lang
const (
	PYTHON Lang = "python"
	C Lang = "c"
	CPLUSPLUS Lang = "cplusplus"
	JAVA Lang = "java"
	CSHARP Lang = "csharp"
	VISUALBASIC Lang = "visualbasic"
	JAVASCRIPT Lang = "javascript"
	SQL Lang = "sql"
	ASM Lang = "asm"
	PHP Lang = "php"
	R Lang = "r"
	GO Lang = "go"
	MATLAB Lang = "matlab"
	SWIFT Lang = "swift"
	DELPHI Lang = "delphi"
	RUBY Lang = "ruby"
	PERL Lang = "perl"
	OBJC Lang = "objc"
	RUST Lang = "rust"
)
