/*
 * ai-proto
 *
 * ai proto for coder
 *
 * API version: 0.0.2
 * Contact: panleiming@linksaas.pro
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

type ErrInfo struct {

	// 错误信息
	ErrMsg string `json:"errMsg,omitempty"`
}
