/*
 * ai-proto
 *
 * ai proto for coder
 *
 * API version: 0.0.2
 * Contact: panleiming@linksaas.pro
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name        string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method      string
	// Pattern is the pattern of the URI.
	Pattern     string
	// HandlerFunc is the handler function of this route.
	HandlerFunc gin.HandlerFunc
}

// Routes is the list of the generated Route.
type Routes []Route

// NewRouter returns a new router.
func NewRouter() *gin.Engine {
	router := gin.Default()
	for _, route := range routes {
		switch route.Method {
		case http.MethodGet:
			router.GET(route.Pattern, route.HandlerFunc)
		case http.MethodPost:
			router.POST(route.Pattern, route.HandlerFunc)
		case http.MethodPut:
			router.PUT(route.Pattern, route.HandlerFunc)
		case http.MethodPatch:
			router.PATCH(route.Pattern, route.HandlerFunc)
		case http.MethodDelete:
			router.DELETE(route.Pattern, route.HandlerFunc)
		}
	}

	return router
}

// Index is the index handler.
func Index(c *gin.Context) {
	c.String(http.StatusOK, "Hello World!")
}

var routes = Routes{
	{
		"Index",
		http.MethodGet,
		"/",
		Index,
	},

	{
		"ApiCodingCompleteLangPost",
		http.MethodPost,
		"/api/coding/complete/:lang",
		ApiCodingCompleteLangPost,
	},

	{
		"ApiCodingConvertLangPost",
		http.MethodPost,
		"/api/coding/convert/:lang",
		ApiCodingConvertLangPost,
	},

	{
		"ApiCodingExplainLangPost",
		http.MethodPost,
		"/api/coding/explain/:lang",
		ApiCodingExplainLangPost,
	},

	{
		"ApiCodingFixErrorLangPost",
		http.MethodPost,
		"/api/coding/fixError/:lang",
		ApiCodingFixErrorLangPost,
	},

	{
		"ApiCodingGenTestLangPost",
		http.MethodPost,
		"/api/coding/genTest/:lang",
		ApiCodingGenTestLangPost,
	},

	{
		"ApiDevCapPost",
		http.MethodPost,
		"/api/dev/cap",
		ApiDevCapPost,
	},

	{
		"ApiDevGenTokenPost",
		http.MethodPost,
		"/api/dev/genToken",
		ApiDevGenTokenPost,
	},
}
